---
- name: Installs Packages
  hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:
  - name: Install telnet
    package:
      name: "{{item}}"
      state: latest  #present # restarted
    with_items: 
    - telnet
    - gzip
    - lftp
    - httpd
    - vsftpd