---
- hosts: all
  become: true
  vars:
    - db_pass: password
    - db_user: wpuser
    - domain: example
    - db_name: wp_{{ domain }}_db
    - root_db_pass: password

  roles:
    - ../../wordpress